apiVersion: apps/v1
kind: Deployment
metadata:
  name: fk-mongodb-hostnet
  namespace: fk-webstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-hostnet
  template:
    metadata:
      labels:
        app: mongodb-hostnet
    spec:
      hostNetwork: true
      nodeName: fk-worker1
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
          hostPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password123
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: fk-mongodb-hostnet
  namespace: fk-webstack
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30017
  selector:
    app: mongodb-hostnet
